# Generated by Django 4.0.1 on 2022-01-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_post_name_alter_post_viewcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='게시판명'),
        ),
    ]
