# Generated by Django 4.0.1 on 2022-02-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(choices=[('직업리뷰', '직업리뷰'), ('학과리뷰', '학과리뷰')], max_length=200, null=True, verbose_name='게시판명'),
        ),
    ]
